# Generated by Django 4.2.6 on 2023-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myPhoto", models.ImageField(upload_to="websites/")),
                ("header", models.CharField(max_length=50)),
                ("briefIntro", models.CharField(max_length=100)),
                ("companyImage", models.ImageField(upload_to="websites/")),
                ("companyName", models.CharField(max_length=50)),
                ("spanOfDate", models.CharField(max_length=50)),
                ("workIntro", models.CharField(max_length=1000)),
            ],
        ),
    ]
