# Generated by Django 4.2.6 on 2023-10-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chewing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chew", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChronicalDiseases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diseases", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Drinking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drink", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Smoking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smoke", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Symptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="homepage",
            name="briefIntro",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="companyImage",
            field=models.ImageField(upload_to="websites/images/"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="header",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="myPhoto",
            field=models.ImageField(upload_to="websites/images/"),
        ),
        migrations.CreateModel(
            name="Healthcheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(choices=[("男", "男"), ("女", "女")], max_length=10),
                ),
                ("security_number", models.CharField(max_length=10, unique=True)),
                ("birthday", models.DateField()),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("check_date", models.DateField()),
                ("formerJob", models.CharField(max_length=200)),
                ("formerJob_start", models.DateField()),
                ("formerJob_end", models.DateField()),
                ("formerJob_totalTime", models.CharField(max_length=200)),
                ("currentJob", models.CharField(max_length=200)),
                ("currentJob_start", models.DateField()),
                ("currentJob_end", models.DateField()),
                ("currentJob_totalTime", models.CharField(max_length=200)),
                ("workHourLastMonth", models.PositiveIntegerField()),
                ("workHourLastSixMonth", models.PositiveIntegerField()),
                (
                    "checkReason",
                    models.CharField(
                        choices=[("新進員工（受僱時）", "新進員工（受僱時）"), ("定期檢查", "定期檢查")],
                        max_length=20,
                    ),
                ),
                ("cancer", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "diagnosed",
                    models.CharField(
                        blank=True,
                        choices=[("是", "是"), ("否", "否")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("doctor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "familyHistory",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("smokequantity", models.PositiveIntegerField(blank=True, null=True)),
                ("smokeyears", models.PositiveIntegerField(blank=True, null=True)),
                ("smokequityear", models.PositiveIntegerField(blank=True, null=True)),
                ("smikequitmonth", models.PositiveIntegerField(blank=True, null=True)),
                ("chewquantity", models.PositiveIntegerField(blank=True, null=True)),
                ("chewyears", models.PositiveIntegerField(blank=True, null=True)),
                ("chewquityear", models.PositiveIntegerField(blank=True, null=True)),
                ("chewquitmonth", models.PositiveIntegerField(blank=True, null=True)),
                ("drinktimes", models.PositiveIntegerField(blank=True, null=True)),
                ("wine", models.CharField(blank=True, max_length=50, null=True)),
                ("drinkquantity", models.PositiveIntegerField(blank=True, null=True)),
                ("drinkquityear", models.PositiveIntegerField(blank=True, null=True)),
                ("drinkquitmonth", models.PositiveIntegerField(blank=True, null=True)),
                ("sleeptime", models.PositiveIntegerField()),
                (
                    "othersymptoms",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "betelnutHabbit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="websites.chewing",
                    ),
                ),
                ("chronicals", models.ManyToManyField(to="websites.chronicaldiseases")),
                (
                    "drinkingHabbit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="websites.drinking",
                    ),
                ),
                ("selfSymptoms", models.ManyToManyField(to="websites.symptoms")),
                (
                    "smokeHabbit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="websites.smoking",
                    ),
                ),
            ],
        ),
    ]
