# Generated by Django 4.2.6 on 2023-10-11 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "websites",
            "0002_chewing_chronicaldiseases_drinking_smoking_symptoms_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcheck",
            name="currentJob_totalTime",
        ),
        migrations.RemoveField(
            model_name="healthcheck",
            name="formerJob_totalTime",
        ),
    ]
